### PR TITLE
Returning function result

### PR DESCRIPTION
**Pull request by wolph**
With this fix the decorator will return the result from the original function so it can be used as a drop-in decorator for functions that return a value.

### CODE REVIEW

**Review by junnaka51 — APPROVED** [review]
@wolph Thank you so much! :)

**Comment by wolph** [comment]
I've got a few other suggestions as well if you're interested.

1. Add the median result (or even configurable 50%, 90%, etc.)
2. Add the option to skip the first or first few iterations to warm up. In the case of numba the first iteration is slow due to compilation.

**Comment by junnaka51** [comment]
@wolph 
Thank you for the suggestions! The both sound reasonable :)

**Comment by wolph** [comment]
I've created a new [pull request](https://github.com/junnaka51/performance_tester/pull/3) that incorporate these changes as well :)

**Pull request merged**
